# Generated by Django 2.0.6 on 2018-06-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rate',
            field=models.CharField(default='Free', help_text=' eg. $100 available at Koala, etc', max_length=200),
        ),
    ]
