# Generated by Django 2.0.6 on 2018-06-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='addressline2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='addressline3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='lattitude',
            field=models.FloatField(blank=True, help_text='Google maps cordinates of the place. <a href="https://support.google.com/maps/answer/18539?co=GENIE.Platform%3DAndroid&hl=en&oco=1" target=_blank style="font-size:120%">visit here for help</a> ', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, help_text='<a href="https://support.google.com/maps/answer/18539?co=GENIE.Platform%3DAndroid&hl=en&oco=1" target=_blank style="font-size:120%">visit here for help</a> on how to Get these values', null=True),
        ),
    ]
