# Generated by Django 2.0.6 on 2018-06-15 08:39

import about.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('comp_year', models.IntegerField(verbose_name='Year of Completion')),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=14)),
                ('portfolio', models.TextField(default='No Bio Available', verbose_name='brief description')),
                ('h', models.IntegerField(default=10, help_text='do not touch this')),
                ('w', models.IntegerField(default=10, help_text='do not touch this')),
                ('profile_pic', models.ImageField(height_field='h', upload_to=about.models.set_upload_path, width_field='w')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_office', models.DateField(default=datetime.date(2018, 8, 1), verbose_name='Office Commencement')),
                ('position_name', models.CharField(choices=[('PR', 'President'), ('VP', 'Vice-President'), ('GS', 'General Secretary'), ('OS', 'Organizing Secretary'), ('FS', 'Financial Secretary'), ('RO', 'Public Relations'), ('EC', 'Electoral Commisioner')], max_length=2, unique_for_year='in_office', verbose_name='Position held')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.OneToOneField(limit_choices_to={'person': None}, on_delete=django.db.models.deletion.CASCADE, to='about.Position'),
        ),
    ]
